// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    'IHeroiconsOutline:home': typeof import('~icons/heroicons-outline/home')['default']
    'IHeroiconsOutline:userCircle': typeof import('~icons/heroicons-outline/user-circle')['default']
    'IMdi:cog': typeof import('~icons/mdi/cog')['default']
    'ISimpleIcons:imdb': typeof import('~icons/simple-icons/imdb')['default']
    'ISimpleIcons:steam': typeof import('~icons/simple-icons/steam')['default']
  }
}

export { }
