// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BasePage: typeof import('./src/components/BasePage.vue')['default']
    CodeGraphql: typeof import('./src/components/CodeGraphql.vue')['default']
    CodeInit: typeof import('./src/components/CodeInit.vue')['default']
    'CodeInit copy': typeof import('./src/components/CodeInit copy.vue')['default']
    'IHeroiconsOutline:clipboardCopy': typeof import('~icons/heroicons-outline/clipboard-copy')['default']
    'IHeroiconsOutline:home': typeof import('~icons/heroicons-outline/home')['default']
    'IHeroiconsOutline:userCircle': typeof import('~icons/heroicons-outline/user-circle')['default']
    'ISimpleIcons:github': typeof import('~icons/simple-icons/github')['default']
    'ISimpleIcons:imdb': typeof import('~icons/simple-icons/imdb')['default']
    'ISimpleIcons:steam': typeof import('~icons/simple-icons/steam')['default']
    ProductPage: typeof import('./src/components/ProductPage.vue')['default']
  }
}

export { }
